# Generated by Django 4.0 on 2021-12-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('org_number', models.CharField(max_length=255, verbose_name="organisation's number")),
                ('address_1', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('zip_code', models.CharField(blank=True, max_length=255, verbose_name='zip code')),
                ('place', models.CharField(blank=True, max_length=255, verbose_name='place')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='country')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='contact person')),
                ('contact_reference', models.CharField(blank=True, max_length=255, verbose_name='contact reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='auth.user')),
            ],
        ),
    ]
